server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.31.21:3306/car?useUnicode=true&characterEncoding=UTF8&useSSL=false=Asia/Shanghai
    hikari:
      username: mxp
      password: root
      minimum-idle: 5
      maximum-pool-size: 20 # ?????????????????10???????((core_count * 2) + effective_spindle_count)
      idle-timeout: 600000 # ????idle???????????????????retired????:10??
      max-lifetime: 1800000 # ???????????????????????????retired????:30????????????????30????MySQL
      connection-timeout: 60000
      connection-test-query: SELECT 1
      pool-name: demoServerDataSourcePool
      read-only: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    enabled: true
    mode: HTML

mybatis:
  type-aliases-package: com.example.car.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 60000
